name: 'Arvix Daily'

on:
  push:
    branches:    
        - 'main'
  schedule:
    - cron: '0 23 * * *'  # utc+8 7:00
  watch:
    types: started
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v3
      - name: 'IP'
        run: curl ifconfig.me
      - name: 'Setup python'
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests lxml bs4 
      - name: 'Print version'
        run: pip -V
      - name: 'Check'
        env:
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_TOKEN: ${{ secrets.EMAIL_TOKEN }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          KEYWORDS: ${{ secrets.KEYWORDS }}
        run: python src/main.py --email $EMAIL --token $EMAIL_TOKEN --receiver $RECEIVER_EMAIL --keywords $KEYWORDS
